// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AutoGrowTextareaController from "./auto_grow_textarea_controller.js"
application.register("auto-grow-textarea", AutoGrowTextareaController)
